site_name: Manuale Poliamore Milano
site_url: http://127.0.0.1:8000/
nav:
  - Home: index.md
  - Valori: carta_dei_valori.md
  - Regolamento: regolamento.md
  - Segnalazioni: segnalazioni.md
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: assets/logo.jpg
  icon:
    logo: octicons/heart-16

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg