site_name: Manuale Poliamore Milano
site_url: http://127.0.0.1:8000/
repo_url: https://github.com/LuchiLucs/manuale-poliamore-milano/
repo_name: manuale-poliamore-milano
edit_uri: edit/master/docs/
nav:
  - Manuale:
    - Benvenute: manuale/benvenute.md
    - Meta Manuale: manuale/meta_manuale.md
  - Valori: carta_dei_valori.md
  - Regolamento: regolamento.md
  - Segnalazioni: segnalazioni.md
  - Gruppo Telegram: gruppo_telegram.md
  - Eventi:
    - Poliaperitivo: events/poli_aperitivo.md
    - Aperitivo Antispecista: events/aperitivo_antispecista.md
    - Cerchio di confronto: events/cerchio_di_confronto.md
theme:
  language: it
  name: material
  #custom_dir: overrides
  font: false
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: assets/logo.jpg
  icon:
    logo: octicons/heart-16
    edit: material/pencil 
    view: material/eye
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.view
    - content.action.edit
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#instant-loading
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    # - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra_css:
  - assets/stylesheets/extra.css
extra:
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#setting-up-versioning
  version:
    provider: mike
  # remove mkdocs-material support link
  generator: false
  # social links
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/poliamoremilano/
      name: Poliamore Milano su Instagram
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/poliamoremilano/
      name: Poliamore Milano su Facebook
copyright: Copyright &copy; 2025 Poliamore Milano con amore
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # Emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - search
  - redirects:
      redirect_maps: 
        'index.md': 'manuale/benvenute.md'
  - git-revision-date-localized:
      enable_creation_date: true